DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS ORDERITEMS;

CREATE TABLE USERS (
    id UUID PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE PRODUCTS (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE ORDERS (
    id UUID PRIMARY KEY,
    date DATE,

    user_id UUID,
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE ORDERITEMS (
    id UUID PRIMARY KEY,
    quantity INT NOT NULL,

    order_id UUID NOT NULL,
    product_id UUID NOT NULL,
    FOREIGN KEY (order_id) REFERENCES ORDERS(id),
    FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);